name: publish-crate

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

jobs:
  crate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Publish tote"
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        polling_interval_seconds: 30
        command: cargo publish